"""
Default ISA-aligned spec sheet templates, one per major instrument type.
Each template maps field labels → UDF slots (udf_01 … udf_100).
Seeded on first call to POST /api/v1/datasheet/templates/seed.
"""
from __future__ import annotations


def _f(udf: str, label: str, section: str, ftype: str,
       options: list[str] | None = None, placeholder: str | None = None) -> dict:
    d: dict = {"udf": udf, "label": label, "section": section, "type": ftype}
    if options:
        d["options"] = options
    if placeholder:
        d["placeholder"] = placeholder
    return d


# ── Common option lists ────────────────────────────────────────────────────────

_BODY_MAT   = ["CS (ASTM A105)", "SS 316L", "SS 316", "SS 304",
                "Hastelloy C-276", "Duplex 2205", "Super Duplex 2507",
                "Monel 400", "Inconel 625", "Titanium Gr. 2", "GRE"]
_POWER      = ["24 VDC (2-wire loop-powered)", "24 VDC (4-wire)",
                "110 VAC 50 Hz", "220 VAC 50 Hz"]
_SIGNAL     = ["4–20 mA", "4–20 mA + HART 5", "4–20 mA + HART 7",
                "Foundation Fieldbus H1", "Profibus PA",
                "WirelessHART", "Pulse / Frequency", "Digital (24 VDC)"]
_PROTOCOL   = ["HART 5", "HART 7", "Foundation Fieldbus H1",
                "Profibus PA", "Profibus DP", "Modbus RTU", "WirelessHART"]
_IP         = ["IP54", "IP65", "IP66", "IP67", "IP68", "NEMA 4", "NEMA 4X"]
_HAZOC      = ["Zone 0", "Zone 1", "Zone 2",
                "Division 1", "Division 2", "Safe Area / NHA"]
_GAS_GRP    = ["IIA", "IIB", "IIC", "Group B", "Group C", "Group D"]
_TEMP_CLS   = ["T1 (450 °C)", "T2 (300 °C)", "T3 (200 °C)",
                "T4 (135 °C)", "T5 (100 °C)", "T6 (85 °C)"]
_EX_METH    = ["Ex ia IIC", "Ex ib IIC", "Ex d IIC", "Ex e IIC",
                "Ex nA IIC", "Ex p IIC"]
_CERT       = ["ATEX", "IECEx", "CSA", "FM", "INMETRO", "PESO"]
_P_RATING   = ["ANSI 150 #", "ANSI 300 #", "ANSI 600 #",
                "ANSI 900 #", "ANSI 1500 #", "ANSI 2500 #",
                "PN 16", "PN 25", "PN 40", "PN 63", "PN 100", "PN 160"]
_P_CONN     = ["½\" NPT", "¾\" NPT", "1\" NPT", "1½\" NPT", "2\" NPT",
                "Flanged 1\" RF", "Flanged 1\" RTJ",
                "Flanged 1½\" RF", "Flanged 2\" RF", "Flanged 2\" RTJ",
                "Socket weld ½\"", "Butt weld"]
_PRESS_UNIT = ["barg", "bara", "psig", "psia", "kPag", "MPag",
                "mmH₂O", "inH₂O", "kg/cm²g"]
_TEMP_UNIT  = ["°C", "°F", "K"]
_PHASE      = ["Gas", "Liquid", "Two-phase", "Steam", "Vapour", "Slurry"]
_FAIL       = ["Fail-Closed (FC)", "Fail-Open (FO)", "Fail-Last (FL)"]
_ACT_TYPE   = ["Spring-and-diaphragm (pneumatic)", "Double-acting cylinder (pneumatic)",
                "Single-acting cylinder (spring-return)", "Electric motor (EMA)",
                "Hydraulic cylinder"]
_MOUNT      = ["Direct (in-line)", "2\" pipe stand (horizontal)",
                "2\" pipe stand (vertical)", "Remote (wall bracket)",
                "Panel mount", "Yoke mount"]
_MANIFOLD   = ["None", "2-valve (isolation)", "3-valve (block-and-bleed)",
                "5-valve (DP service)"]
_METER_PRIN = ["Differential Pressure (orifice)", "Differential Pressure (Annubar)",
                "Vortex shedding", "Magnetic (electromagnetic)",
                "Coriolis (mass)", "Turbine", "Ultrasonic (transit-time)",
                "Positive displacement", "Rotameter (variable-area)"]
_LEVEL_PRIN = ["Guided Wave Radar (GWR)", "Free-space Radar (FMCW)",
                "Differential Pressure (DP)", "Displacer",
                "Float", "Magnetostrictive", "Capacitance", "Hydrostatic"]
_SENSOR_TYP = ["Thermocouple Type K (NiCr/NiAl)",
                "Thermocouple Type J (Fe/CuNi)",
                "Thermocouple Type T (Cu/CuNi)",
                "Thermocouple Type E (NiCr/CuNi)",
                "Thermocouple Type N (NiCrSi/NiSi)",
                "RTD Pt-100 (2-wire)", "RTD Pt-100 (3-wire)", "RTD Pt-100 (4-wire)",
                "RTD Pt-1000 (3-wire)", "RTD Pt-500 (3-wire)"]
_SHANK      = ["Straight (constant bore)", "Stepped (tapered tip)",
                "Tapered (full taper)", "Reduced tip"]
_TRIM_MAT   = ["SS 316", "SS 316L", "Stellite (Co-Cr alloy)",
                "Tungsten carbide", "Ceramic (Al₂O₃)", "Nitrided SS 316"]
_LEAK_CLASS = ["ANSI/FCI 70-2 Class I", "ANSI/FCI 70-2 Class II",
                "ANSI/FCI 70-2 Class III", "ANSI/FCI 70-2 Class IV",
                "ANSI/FCI 70-2 Class V", "ANSI/FCI 70-2 Class VI",
                "ISO 5208 Grade A", "ISO 5208 Grade B",
                "ISO 5208 Grade C", "ISO 5208 Grade D"]
_VALVE_TYPE = ["Globe (single-port)", "Globe (double-port)",
                "Rotary (ball)", "Rotary (butterfly – wafer)",
                "Rotary (butterfly – double flanged)",
                "Rotary (eccentric – Camflex)",
                "3-way diverting", "3-way mixing"]
_END_CONN   = ["Flanged RF", "Flanged RTJ", "Butt-weld", "Socket-weld",
                "Screwed NPT", "Wafer (lug)", "Wafer (through-bolt)"]
_TRIM_TYPE  = ["Standard", "Characterized (equal %)", "Characterized (linear)",
                "Noise attenuating (multistage)", "Anti-cavitation (multistage)",
                "Low-noise rotary", "Soft-seat (PTFE)"]
_OPEN_TYPE  = ["Normally-Open (NO)", "Normally-Closed (NC)"]
_FS_RATE    = ["None", "API 6FA", "API 607", "BS 6755 Pt 2", "ISO 10497"]
_PSV_TYPE   = ["Conventional (open bonnet)", "Balanced bellows", "Pilot-operated (POPRV)",
                "Rupture disc + PRV in series"]
_API_OR     = ["D (0.110 in²)", "E (0.196 in²)", "F (0.307 in²)",
                "G (0.503 in²)", "H (0.785 in²)", "J (1.287 in²)",
                "K (1.838 in²)", "L (2.853 in²)", "M (3.600 in²)",
                "N (4.340 in²)", "P (6.380 in²)", "Q (11.05 in²)",
                "R (16.00 in²)", "T (26.00 in²)"]
_ORIFICE_TYPE = ["Concentric square-edge (standard)",
                  "Eccentric (dirty service)", "Segmental (wet gas/liquid)",
                  "Quadrant-edge (low Re)", "Conical entrance (low Re)"]
_TAP_TYPE   = ["Flange taps (25 mm from face)", "Vena contracta taps",
                "Corner taps", "D and D/2 taps", "Pipe taps (2½D & 8D)"]


# ── PT — Pressure Transmitter ─────────────────────────────────────────────────
PT_FIELDS = [
    # Identification
    _f("udf_01", "Service Description",    "Identification",  "text",   placeholder="e.g. HP separator inlet pressure"),
    _f("udf_02", "P&ID Number",            "Identification",  "text"),
    _f("udf_03", "Line / Equipment Tag",   "Identification",  "text"),
    # Process Data
    _f("udf_04", "Fluid",                  "Process Data",    "text",   placeholder="e.g. Natural Gas"),
    _f("udf_05", "Fluid State",            "Process Data",    "select", options=_PHASE),
    _f("udf_06", "Operating Pressure",     "Process Data",    "number", placeholder="barg"),
    _f("udf_07", "Design Pressure",        "Process Data",    "number", placeholder="barg"),
    _f("udf_08", "Operating Temperature",  "Process Data",    "number", placeholder="°C"),
    _f("udf_09", "Design Temperature",     "Process Data",    "number", placeholder="°C"),
    # Instrument Body
    _f("udf_10", "Manufacturer",           "Instrument Body", "text",   placeholder="e.g. Emerson / ABB / Yokogawa"),
    _f("udf_11", "Model Number",           "Instrument Body", "text"),
    _f("udf_12", "Body Material",          "Instrument Body", "select", options=_BODY_MAT),
    _f("udf_13", "Process Connection",     "Instrument Body", "select", options=_P_CONN),
    _f("udf_14", "Pressure Rating",        "Instrument Body", "select", options=_P_RATING),
    # Sensing Element
    _f("udf_15", "Diaphragm Material",     "Sensing Element", "select",
       options=["SS 316L", "Hastelloy C-276", "Tantalum", "Monel 400", "Gold-plated SS"]),
    _f("udf_16", "Fill Fluid",             "Sensing Element", "select",
       options=["Silicone oil", "Inert oil (Halocarbon)", "Glycerin/water", "High-temp synthetic"]),
    # Electrical
    _f("udf_17", "Power Supply",           "Electrical",      "select", options=_POWER),
    _f("udf_18", "Output Signal",          "Electrical",      "select", options=_SIGNAL),
    _f("udf_19", "Communication Protocol", "Electrical",      "select", options=_PROTOCOL),
    _f("udf_20", "Enclosure IP Rating",    "Electrical",      "select", options=_IP),
    # Calibration
    _f("udf_21", "Range — Min",            "Calibration",     "number", placeholder="Lower value"),
    _f("udf_22", "Range — Max",            "Calibration",     "number", placeholder="Upper value"),
    _f("udf_23", "Range Unit",             "Calibration",     "select", options=_PRESS_UNIT),
    _f("udf_24", "Alarm High (PAH)",       "Calibration",     "number"),
    _f("udf_25", "Alarm Low (PAL)",        "Calibration",     "number"),
    _f("udf_26", "Trip High (PAHH)",       "Calibration",     "number"),
    _f("udf_27", "Trip Low (PALL)",        "Calibration",     "number"),
    _f("udf_28", "Accuracy",               "Calibration",     "text",   placeholder="e.g. ±0.075 % span"),
    # Hazardous Area
    _f("udf_29", "Area Classification",    "Hazardous Area",  "select", options=_HAZOC),
    _f("udf_30", "Gas Group",              "Hazardous Area",  "select", options=_GAS_GRP),
    _f("udf_31", "Temperature Class",      "Hazardous Area",  "select", options=_TEMP_CLS),
    _f("udf_32", "Protection Method",      "Hazardous Area",  "select", options=_EX_METH),
    _f("udf_33", "Certification Body",     "Hazardous Area",  "select", options=_CERT),
    # Installation
    _f("udf_34", "Mounting",               "Installation",    "select", options=_MOUNT),
    _f("udf_35", "Manifold",               "Installation",    "select", options=_MANIFOLD),
]


# ── PDT — Differential Pressure Transmitter ───────────────────────────────────
PDT_FIELDS = [
    _f("udf_01", "Service Description",    "Identification",  "text"),
    _f("udf_02", "P&ID Number",            "Identification",  "text"),
    _f("udf_03", "Line / Equipment Tag",   "Identification",  "text"),
    _f("udf_04", "Fluid",                  "Process Data",    "text"),
    _f("udf_05", "Fluid State",            "Process Data",    "select", options=_PHASE),
    _f("udf_06", "Operating Pressure (line)","Process Data",  "number", placeholder="barg"),
    _f("udf_07", "Design Pressure",        "Process Data",    "number", placeholder="barg"),
    _f("udf_08", "Operating Temperature",  "Process Data",    "number", placeholder="°C"),
    _f("udf_09", "Design Temperature",     "Process Data",    "number", placeholder="°C"),
    _f("udf_10", "Max DP at Shut-off",     "Process Data",    "number", placeholder="mbar"),
    _f("udf_11", "Manufacturer",           "Instrument Body", "text"),
    _f("udf_12", "Model Number",           "Instrument Body", "text"),
    _f("udf_13", "Body Material",          "Instrument Body", "select", options=_BODY_MAT),
    _f("udf_14", "HP Process Connection",  "Instrument Body", "select", options=_P_CONN),
    _f("udf_15", "LP Process Connection",  "Instrument Body", "select", options=_P_CONN),
    _f("udf_16", "Pressure Rating",        "Instrument Body", "select", options=_P_RATING),
    _f("udf_17", "Diaphragm Material",     "Sensing Element", "select",
       options=["SS 316L", "Hastelloy C-276", "Tantalum", "Monel 400"]),
    _f("udf_18", "Fill Fluid",             "Sensing Element", "select",
       options=["Silicone oil", "Inert oil (Halocarbon)", "High-temp synthetic"]),
    _f("udf_19", "Power Supply",           "Electrical",      "select", options=_POWER),
    _f("udf_20", "Output Signal",          "Electrical",      "select", options=_SIGNAL),
    _f("udf_21", "Communication Protocol", "Electrical",      "select", options=_PROTOCOL),
    _f("udf_22", "Enclosure IP Rating",    "Electrical",      "select", options=_IP),
    _f("udf_23", "DP Range — Min",         "Calibration",     "number", placeholder="Lower value"),
    _f("udf_24", "DP Range — Max",         "Calibration",     "number", placeholder="Upper value"),
    _f("udf_25", "DP Range Unit",          "Calibration",     "select",
       options=["mbar", "mmH₂O", "inH₂O", "kPa", "bar", "psi"]),
    _f("udf_26", "Alarm High (PDAH)",      "Calibration",     "number"),
    _f("udf_27", "Alarm Low (PDAL)",       "Calibration",     "number"),
    _f("udf_28", "Area Classification",    "Hazardous Area",  "select", options=_HAZOC),
    _f("udf_29", "Gas Group",              "Hazardous Area",  "select", options=_GAS_GRP),
    _f("udf_30", "Temperature Class",      "Hazardous Area",  "select", options=_TEMP_CLS),
    _f("udf_31", "Protection Method",      "Hazardous Area",  "select", options=_EX_METH),
    _f("udf_32", "Certification Body",     "Hazardous Area",  "select", options=_CERT),
    _f("udf_33", "Mounting",               "Installation",    "select", options=_MOUNT),
    _f("udf_34", "Manifold",               "Installation",    "select", options=_MANIFOLD),
    _f("udf_35", "Drain / Vent",           "Installation",    "select",
       options=["None", "HP side drain", "LP side vent", "Both sides"]),
]


# ── FT — Flow Transmitter ─────────────────────────────────────────────────────
FT_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "P&ID Number",             "Identification",  "text"),
    _f("udf_03", "Line / Equipment Tag",    "Identification",  "text"),
    _f("udf_04", "Fluid",                   "Process Data",    "text"),
    _f("udf_05", "Fluid State",             "Process Data",    "select", options=_PHASE),
    _f("udf_06", "Density @ Oper. Cond.",   "Process Data",    "number", placeholder="kg/m³"),
    _f("udf_07", "Viscosity",               "Process Data",    "number", placeholder="cP"),
    _f("udf_08", "Operating Pressure",      "Process Data",    "number", placeholder="barg"),
    _f("udf_09", "Operating Temperature",   "Process Data",    "number", placeholder="°C"),
    _f("udf_10", "Design Pressure",         "Process Data",    "number", placeholder="barg"),
    _f("udf_11", "Design Temperature",      "Process Data",    "number", placeholder="°C"),
    _f("udf_12", "Flow — Min",              "Flow",            "number"),
    _f("udf_13", "Flow — Normal",           "Flow",            "number"),
    _f("udf_14", "Flow — Max",              "Flow",            "number"),
    _f("udf_15", "Flow Unit",               "Flow",            "select",
       options=["m³/h", "Sm³/h", "MMSCFD", "kg/h", "t/h", "l/min", "US gpm", "USGPM"]),
    _f("udf_16", "Meter Principle",         "Meter Body",      "select", options=_METER_PRIN),
    _f("udf_17", "Line Size",               "Meter Body",      "text",   placeholder='e.g. 4" / DN100'),
    _f("udf_18", "Pipe Schedule",           "Meter Body",      "text",   placeholder="e.g. Sch 40 / STD"),
    _f("udf_19", "Body Material",           "Meter Body",      "select", options=_BODY_MAT),
    _f("udf_20", "End Connections",         "Meter Body",      "select", options=_END_CONN),
    _f("udf_21", "Pressure Rating",         "Meter Body",      "select", options=_P_RATING),
    _f("udf_22", "Manufacturer",            "Meter Body",      "text"),
    _f("udf_23", "Model Number",            "Meter Body",      "text"),
    _f("udf_24", "Power Supply",            "Electrical",      "select", options=_POWER),
    _f("udf_25", "Output Signal",           "Electrical",      "select", options=_SIGNAL),
    _f("udf_26", "Communication Protocol",  "Electrical",      "select", options=_PROTOCOL),
    _f("udf_27", "Enclosure IP Rating",     "Electrical",      "select", options=_IP),
    _f("udf_28", "Calibrated Range — Min",  "Calibration",     "number"),
    _f("udf_29", "Calibrated Range — Max",  "Calibration",     "number"),
    _f("udf_30", "Alarm High (FAH)",        "Calibration",     "number"),
    _f("udf_31", "Alarm Low (FAL)",         "Calibration",     "number"),
    _f("udf_32", "Area Classification",     "Hazardous Area",  "select", options=_HAZOC),
    _f("udf_33", "Gas Group",              "Hazardous Area",  "select", options=_GAS_GRP),
    _f("udf_34", "Temperature Class",      "Hazardous Area",  "select", options=_TEMP_CLS),
    _f("udf_35", "Protection Method",      "Hazardous Area",  "select", options=_EX_METH),
    _f("udf_36", "Certification Body",     "Hazardous Area",  "select", options=_CERT),
    _f("udf_37", "Upstream Straight Run",   "Installation",    "text",   placeholder="e.g. 20D"),
    _f("udf_38", "Downstream Straight Run", "Installation",    "text",   placeholder="e.g. 5D"),
    _f("udf_39", "Mounting",                "Installation",    "select", options=_MOUNT),
]


# ── FE — Flow Element / Orifice Plate ─────────────────────────────────────────
FE_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "P&ID Number",             "Identification",  "text"),
    _f("udf_03", "Line Tag",                "Identification",  "text"),
    _f("udf_04", "Fluid",                   "Process Data",    "text"),
    _f("udf_05", "Fluid State",             "Process Data",    "select", options=_PHASE),
    _f("udf_06", "Density @ Oper. Cond.",   "Process Data",    "number", placeholder="kg/m³"),
    _f("udf_07", "Viscosity",               "Process Data",    "number", placeholder="cP"),
    _f("udf_08", "Operating Pressure",      "Process Data",    "number", placeholder="barg"),
    _f("udf_09", "Operating Temperature",   "Process Data",    "number", placeholder="°C"),
    _f("udf_10", "Flow — Normal",           "Process Data",    "number"),
    _f("udf_11", "Flow — Max",              "Process Data",    "number"),
    _f("udf_12", "Flow Unit",               "Process Data",    "select",
       options=["m³/h", "Sm³/h", "MMSCFD", "kg/h", "t/h"]),
    _f("udf_13", "Orifice Type",            "Element",         "select", options=_ORIFICE_TYPE),
    _f("udf_14", "Bore Diameter (mm)",      "Element",         "number", placeholder="Calculated bore"),
    _f("udf_15", "Beta Ratio (d/D)",        "Element",         "number", placeholder="e.g. 0.65"),
    _f("udf_16", "Plate Material",          "Element",         "select",
       options=["SS 316L", "SS 316", "Hastelloy C-276", "Monel 400", "Titanium"]),
    _f("udf_17", "Plate Thickness (mm)",    "Element",         "number"),
    _f("udf_18", "Tap Type",                "Element",         "select", options=_TAP_TYPE),
    _f("udf_19", "Line Size (NPS)",         "Piping",          "text",   placeholder='e.g. 6" / DN150'),
    _f("udf_20", "Pipe Schedule",           "Piping",          "text",   placeholder="e.g. Sch 40 / STD"),
    _f("udf_21", "Pipe Inside Diameter (mm)","Piping",         "number"),
    _f("udf_22", "Pipe Material",           "Piping",          "select", options=_BODY_MAT),
    _f("udf_23", "Flange Rating",           "Piping",          "select", options=_P_RATING),
    _f("udf_24", "Upstream Straight Run",   "Installation",    "text",   placeholder="e.g. 20D"),
    _f("udf_25", "Downstream Straight Run", "Installation",    "text",   placeholder="e.g. 5D"),
    _f("udf_26", "Differential Pressure (mbar)","Sizing",      "number", placeholder="DP at normal flow"),
    _f("udf_27", "Discharge Coefficient Cd","Sizing",          "number", placeholder="e.g. 0.6108"),
]


# ── LT — Level Transmitter ────────────────────────────────────────────────────
LT_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "P&ID Number",             "Identification",  "text"),
    _f("udf_03", "Vessel / Equipment Tag",  "Identification",  "text"),
    _f("udf_04", "Fluid",                   "Process Data",    "text"),
    _f("udf_05", "Fluid State",             "Process Data",    "select", options=_PHASE),
    _f("udf_06", "Liquid Density",          "Process Data",    "number", placeholder="kg/m³"),
    _f("udf_07", "Vapour / Gas Density",    "Process Data",    "number", placeholder="kg/m³"),
    _f("udf_08", "Operating Pressure",      "Process Data",    "number", placeholder="barg"),
    _f("udf_09", "Design Pressure",         "Process Data",    "number", placeholder="barg"),
    _f("udf_10", "Operating Temperature",   "Process Data",    "number", placeholder="°C"),
    _f("udf_11", "Design Temperature",      "Process Data",    "number", placeholder="°C"),
    _f("udf_12", "Measuring Principle",     "Instrument",      "select", options=_LEVEL_PRIN),
    _f("udf_13", "Manufacturer",            "Instrument",      "text"),
    _f("udf_14", "Model Number",            "Instrument",      "text"),
    _f("udf_15", "Probe / Antenna Material","Instrument",      "select",
       options=["SS 316L", "Hastelloy C-276", "PP", "PTFE", "Titanium"]),
    _f("udf_16", "Process Connection",      "Instrument",      "select", options=_P_CONN),
    _f("udf_17", "Nozzle Rating",           "Instrument",      "select", options=_P_RATING),
    _f("udf_18", "Bridle / Standpipe",      "Instrument",      "select",
       options=["None (direct mount)", "Bridle required", "Standpipe required"]),
    _f("udf_19", "Zero (LZZ) — mm",         "Calibration",     "number", placeholder="From nozzle CL"),
    _f("udf_20", "Span (mm)",               "Calibration",     "number"),
    _f("udf_21", "LAL (Low Low Alarm)",     "Calibration",     "number", placeholder="mm from datum"),
    _f("udf_22", "LAL (Low Alarm)",         "Calibration",     "number"),
    _f("udf_23", "LAH (High Alarm)",        "Calibration",     "number"),
    _f("udf_24", "LAH (High-High Alarm)",   "Calibration",     "number"),
    _f("udf_25", "Power Supply",            "Electrical",      "select", options=_POWER),
    _f("udf_26", "Output Signal",           "Electrical",      "select", options=_SIGNAL),
    _f("udf_27", "Communication Protocol",  "Electrical",      "select", options=_PROTOCOL),
    _f("udf_28", "Enclosure IP Rating",     "Electrical",      "select", options=_IP),
    _f("udf_29", "Area Classification",     "Hazardous Area",  "select", options=_HAZOC),
    _f("udf_30", "Gas Group",               "Hazardous Area",  "select", options=_GAS_GRP),
    _f("udf_31", "Temperature Class",       "Hazardous Area",  "select", options=_TEMP_CLS),
    _f("udf_32", "Protection Method",       "Hazardous Area",  "select", options=_EX_METH),
    _f("udf_33", "Certification Body",      "Hazardous Area",  "select", options=_CERT),
    _f("udf_34", "Mounting / Orientation",  "Installation",    "select",
       options=["Top nozzle (vertical probe)", "Side nozzle (angled probe)",
                "Bottom nozzle (GWR)", "Top nozzle (GWR)"]),
]


# ── TT — Temperature Transmitter ──────────────────────────────────────────────
TT_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "P&ID Number",             "Identification",  "text"),
    _f("udf_03", "Line / Equipment Tag",    "Identification",  "text"),
    _f("udf_04", "Fluid",                   "Process Data",    "text"),
    _f("udf_05", "Operating Temperature",   "Process Data",    "number", placeholder="°C"),
    _f("udf_06", "Design Temperature",      "Process Data",    "number", placeholder="°C"),
    _f("udf_07", "Operating Pressure",      "Process Data",    "number", placeholder="barg"),
    _f("udf_08", "Design Pressure",         "Process Data",    "number", placeholder="barg"),
    _f("udf_09", "Sensor Type",             "Transmitter",     "select", options=_SENSOR_TYP),
    _f("udf_10", "Number of Sensors",       "Transmitter",     "select",
       options=["1 (simplex)", "2 (duplex, average)", "2 (duplex, select)", "4 (quad)"]),
    _f("udf_11", "Connection Head Material","Transmitter",     "select",
       options=["Al alloy (die-cast)", "SS 316 (cast)", "GJL-250 (grey iron)", "Polycarbonate"]),
    _f("udf_12", "Thermowell Required",     "Transmitter",     "select",
       options=["Yes — specify TW tag", "No — direct insertion"]),
    _f("udf_13", "Thermowell Tag",          "Transmitter",     "text",   placeholder="e.g. TW-101A"),
    _f("udf_14", "Manufacturer",            "Transmitter",     "text"),
    _f("udf_15", "Model Number",            "Transmitter",     "text"),
    _f("udf_16", "Power Supply",            "Electrical",      "select", options=_POWER),
    _f("udf_17", "Output Signal",           "Electrical",      "select", options=_SIGNAL),
    _f("udf_18", "Communication Protocol",  "Electrical",      "select", options=_PROTOCOL),
    _f("udf_19", "Enclosure IP Rating",     "Electrical",      "select", options=_IP),
    _f("udf_20", "Range — Min",             "Calibration",     "number", placeholder="°C"),
    _f("udf_21", "Range — Max",             "Calibration",     "number", placeholder="°C"),
    _f("udf_22", "Alarm High (TAH)",        "Calibration",     "number"),
    _f("udf_23", "Alarm Low (TAL)",         "Calibration",     "number"),
    _f("udf_24", "Trip High (TAHH)",        "Calibration",     "number"),
    _f("udf_25", "Trip Low (TALL)",         "Calibration",     "number"),
    _f("udf_26", "Accuracy",               "Calibration",     "text",   placeholder="e.g. ±0.5 °C"),
    _f("udf_27", "Area Classification",     "Hazardous Area",  "select", options=_HAZOC),
    _f("udf_28", "Gas Group",               "Hazardous Area",  "select", options=_GAS_GRP),
    _f("udf_29", "Temperature Class",       "Hazardous Area",  "select", options=_TEMP_CLS),
    _f("udf_30", "Protection Method",       "Hazardous Area",  "select", options=_EX_METH),
    _f("udf_31", "Certification Body",      "Hazardous Area",  "select", options=_CERT),
    _f("udf_32", "Mounting",                "Installation",    "select", options=_MOUNT),
]


# ── TE — Temperature Element (TC / RTD) ───────────────────────────────────────
TE_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "P&ID Number",             "Identification",  "text"),
    _f("udf_03", "Line / Equipment Tag",    "Identification",  "text"),
    _f("udf_04", "Fluid",                   "Process Data",    "text"),
    _f("udf_05", "Operating Temperature",   "Process Data",    "number", placeholder="°C"),
    _f("udf_06", "Design Temperature",      "Process Data",    "number", placeholder="°C"),
    _f("udf_07", "Operating Pressure",      "Process Data",    "number", placeholder="barg"),
    _f("udf_08", "Sensor Type",             "Element",         "select", options=_SENSOR_TYP),
    _f("udf_09", "Number of Elements",      "Element",         "select",
       options=["Single (simplex)", "Dual (duplex)", "Triple"]),
    _f("udf_10", "Sheath Material",         "Element",         "select",
       options=["SS 316 (AISI 316)", "Inconel 600", "Inconel 625",
                "Hastelloy C-276", "Titanium", "PTFE-coated SS"]),
    _f("udf_11", "Sheath Diameter (mm)",    "Element",         "number", placeholder="e.g. 6, 8, 11"),
    _f("udf_12", "Element Length (mm)",     "Element",         "number", placeholder="Active element length"),
    _f("udf_13", "Mineral Insulation",      "Element",         "select",
       options=["MgO (Magnesium oxide)", "Al₂O₃ (Aluminium oxide)"]),
    _f("udf_14", "Connection Head Type",    "Head",            "select",
       options=["Form B (round)", "Form C (rectangular)", "Form D (mini round)", "Terminal block"]),
    _f("udf_15", "Connection Head Material","Head",            "select",
       options=["Al alloy (die-cast)", "SS 316 (cast)", "GJL-250 (grey iron)"]),
    _f("udf_16", "Cable Entry Size",        "Head",            "select",
       options=["M20 × 1.5", "M25 × 1.5", "½\" NPT", "¾\" NPT"]),
    _f("udf_17", "Thermowell Required",     "Thermowell",      "select",
       options=["Yes", "No (bare insertion)"]),
    _f("udf_18", "Thermowell Process Conn.","Thermowell",      "select", options=_P_CONN),
    _f("udf_19", "Thermowell Rating",       "Thermowell",      "select", options=_P_RATING),
    _f("udf_20", "Thermowell Material",     "Thermowell",      "select", options=_BODY_MAT),
    _f("udf_21", "Insertion Length U (mm)", "Thermowell",      "number"),
    _f("udf_22", "Lagging Extension (mm)",  "Thermowell",      "number", placeholder="0 if none"),
    _f("udf_23", "Area Classification",     "Hazardous Area",  "select", options=_HAZOC),
    _f("udf_24", "Gas Group",               "Hazardous Area",  "select", options=_GAS_GRP),
    _f("udf_25", "Protection Method",       "Hazardous Area",  "select", options=_EX_METH),
]


# ── TW — Thermowell ───────────────────────────────────────────────────────────
TW_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "Associated TE / TT Tag",  "Identification",  "text"),
    _f("udf_03", "Line / Equipment Tag",    "Identification",  "text"),
    _f("udf_04", "Fluid",                   "Process Data",    "text"),
    _f("udf_05", "Operating Pressure",      "Process Data",    "number", placeholder="barg"),
    _f("udf_06", "Design Pressure",         "Process Data",    "number", placeholder="barg"),
    _f("udf_07", "Operating Temperature",   "Process Data",    "number", placeholder="°C"),
    _f("udf_08", "Process Fluid Velocity",  "Process Data",    "number", placeholder="m/s"),
    _f("udf_09", "Thermowell Material",     "Thermowell Body", "select", options=_BODY_MAT),
    _f("udf_10", "Shank Type",              "Thermowell Body", "select", options=_SHANK),
    _f("udf_11", "Process Connection Type", "Thermowell Body", "select",
       options=["Threaded NPT", "Threaded BSPT", "Flanged RF", "Flanged RTJ",
                "Socket weld", "Weld-in (Van Stone)"]),
    _f("udf_12", "Process Connection Size", "Thermowell Body", "text",   placeholder='e.g. ¾" / DN20'),
    _f("udf_13", "Pressure Rating",         "Thermowell Body", "select", options=_P_RATING),
    _f("udf_14", "Bore Diameter (mm)",      "Thermowell Body", "number", placeholder="e.g. 8.0"),
    _f("udf_15", "Root Diameter (mm)",      "Thermowell Body", "number"),
    _f("udf_16", "Tip Diameter (mm)",       "Thermowell Body", "number"),
    _f("udf_17", "Insertion Length U (mm)", "Dimensions",      "number", placeholder="Process insertion"),
    _f("udf_18", "Immersion Length T (mm)", "Dimensions",      "number"),
    _f("udf_19", "Lagging Extension (mm)",  "Dimensions",      "number", placeholder="0 if none"),
    _f("udf_20", "Overall Length N (mm)",   "Dimensions",      "number"),
    _f("udf_21", "Natural Frequency (Hz)",  "Wake Frequency",  "number", placeholder="ASME PTC 19.3"),
    _f("udf_22", "Damping Ratio",           "Wake Frequency",  "number"),
    _f("udf_23", "Wake Freq. Check Result", "Wake Frequency",  "select",
       options=["PASS", "FAIL — redesign required", "N/A (low velocity)"]),
    _f("udf_24", "Manufacturer",            "Vendor",          "text"),
    _f("udf_25", "Model / Part Number",     "Vendor",          "text"),
]


# ── FCV — Control Valve (covers LCV, PCV, TCV) ───────────────────────────────
FCV_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "P&ID Number",             "Identification",  "text"),
    _f("udf_03", "Line Tag",                "Identification",  "text"),
    _f("udf_04", "Fluid",                   "Process Data",    "text"),
    _f("udf_05", "Fluid State",             "Process Data",    "select", options=_PHASE),
    _f("udf_06", "P1 — Inlet Pressure",     "Process Data",    "number", placeholder="barg"),
    _f("udf_07", "P2 — Outlet Pressure",    "Process Data",    "number", placeholder="barg"),
    _f("udf_08", "ΔP across valve",         "Process Data",    "number", placeholder="bar"),
    _f("udf_09", "Fluid Density",           "Process Data",    "number", placeholder="kg/m³"),
    _f("udf_10", "Viscosity",               "Process Data",    "number", placeholder="cP"),
    _f("udf_11", "Vapour Pressure",         "Process Data",    "number", placeholder="bara"),
    _f("udf_12", "Inlet Temperature",       "Process Data",    "number", placeholder="°C"),
    _f("udf_13", "Design Pressure",         "Process Data",    "number", placeholder="barg"),
    _f("udf_14", "Design Temperature",      "Process Data",    "number", placeholder="°C"),
    _f("udf_15", "Flow — Minimum",          "Sizing",          "number"),
    _f("udf_16", "Flow — Normal",           "Sizing",          "number"),
    _f("udf_17", "Flow — Maximum",          "Sizing",          "number"),
    _f("udf_18", "Flow Unit",               "Sizing",          "select",
       options=["m³/h", "Sm³/h", "kg/h", "t/h", "l/min", "US gpm"]),
    _f("udf_19", "Cv Required",             "Sizing",          "number", placeholder="Calculated"),
    _f("udf_20", "Cv Selected",             "Sizing",          "number", placeholder="From datasheet"),
    _f("udf_21", "Opening at Normal (%)",   "Sizing",          "number", placeholder="Target 40–80 %"),
    _f("udf_22", "Valve Type",              "Valve Body",      "select", options=_VALVE_TYPE),
    _f("udf_23", "Valve Body Size",         "Valve Body",      "text",   placeholder='e.g. 4" / DN100'),
    _f("udf_24", "Body Material",           "Valve Body",      "select", options=_BODY_MAT),
    _f("udf_25", "End Connections",         "Valve Body",      "select", options=_END_CONN),
    _f("udf_26", "Pressure Rating",         "Valve Body",      "select", options=_P_RATING),
    _f("udf_27", "Face-to-Face (mm)",       "Valve Body",      "number"),
    _f("udf_28", "Trim Type",               "Trim",            "select", options=_TRIM_TYPE),
    _f("udf_29", "Seat Material",           "Trim",            "select", options=_TRIM_MAT),
    _f("udf_30", "Plug / Disc Material",    "Trim",            "select", options=_TRIM_MAT),
    _f("udf_31", "Stem Material",           "Trim",            "select",
       options=["SS 316", "17-4 PH SS", "Inconel 625", "Hastelloy C-276"]),
    _f("udf_32", "Leakage Class",           "Trim",            "select", options=_LEAK_CLASS),
    _f("udf_33", "Actuator Type",           "Actuator",        "select", options=_ACT_TYPE),
    _f("udf_34", "Fail Position",           "Actuator",        "select", options=_FAIL),
    _f("udf_35", "Handwheel",               "Actuator",        "select",
       options=["Not required", "Side-mount (manual)", "Top-mount (manual)", "Gearbox"]),
    _f("udf_36", "Air Supply Pressure",     "Actuator",        "number", placeholder="barg"),
    _f("udf_37", "Bench Set",               "Actuator",        "text",   placeholder="e.g. 0.3–1.5 barg"),
    _f("udf_38", "Positioner Required",     "Positioner",      "select", options=["Yes", "No"]),
    _f("udf_39", "Positioner Manufacturer", "Positioner",      "text"),
    _f("udf_40", "Positioner Model",        "Positioner",      "text"),
    _f("udf_41", "Positioner Signal",       "Positioner",      "select", options=_SIGNAL),
    _f("udf_42", "Solenoid Valve",          "Accessories",     "select",
       options=["Not required", "NAMUR SIL 2", "NAMUR SIL 3", "Dual SOV"]),
    _f("udf_43", "Limit Switches",          "Accessories",     "select",
       options=["Not required", "2 SPDT (OPEN/CLOSED)", "NAMUR proximity sensor", "Inductive sensor"]),
    _f("udf_44", "Volume Booster",          "Accessories",     "select", options=["Not required", "1:1 ratio", "4:1 ratio"]),
    _f("udf_45", "Power Supply",            "Electrical",      "select", options=_POWER),
    _f("udf_46", "Control Signal",          "Electrical",      "select", options=_SIGNAL),
    _f("udf_47", "Enclosure IP Rating",     "Electrical",      "select", options=_IP),
    _f("udf_48", "Area Classification",     "Hazardous Area",  "select", options=_HAZOC),
    _f("udf_49", "Gas Group",               "Hazardous Area",  "select", options=_GAS_GRP),
    _f("udf_50", "Temperature Class",       "Hazardous Area",  "select", options=_TEMP_CLS),
    _f("udf_51", "Protection Method",       "Hazardous Area",  "select", options=_EX_METH),
    _f("udf_52", "Certification Body",      "Hazardous Area",  "select", options=_CERT),
    _f("udf_53", "Manufacturer",            "Vendor",          "text"),
    _f("udf_54", "Model / Part Number",     "Vendor",          "text"),
]


# ── SDV — Shutdown Valve (covers BDV, XV, MOV) ───────────────────────────────
SDV_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "P&ID Number",             "Identification",  "text"),
    _f("udf_03", "Line Tag",                "Identification",  "text"),
    _f("udf_04", "SIL Level",               "Identification",  "select",
       options=["None (QEQ)", "SIL 1", "SIL 2", "SIL 3"]),
    _f("udf_05", "Fluid",                   "Process Data",    "text"),
    _f("udf_06", "Fluid State",             "Process Data",    "select", options=_PHASE),
    _f("udf_07", "Operating Pressure",      "Process Data",    "number", placeholder="barg"),
    _f("udf_08", "Design Pressure",         "Process Data",    "number", placeholder="barg"),
    _f("udf_09", "Operating Temperature",   "Process Data",    "number", placeholder="°C"),
    _f("udf_10", "Design Temperature",      "Process Data",    "number", placeholder="°C"),
    _f("udf_11", "Valve Type",              "Valve Body",      "select",
       options=["Ball (full-bore)", "Ball (reduced-bore)", "Ball (double-block & bleed)",
                "Butterfly (triple-offset)", "Gate", "Plug"]),
    _f("udf_12", "Valve Size",              "Valve Body",      "text",   placeholder='e.g. 6" / DN150'),
    _f("udf_13", "Body Material",           "Valve Body",      "select", options=_BODY_MAT),
    _f("udf_14", "End Connections",         "Valve Body",      "select", options=_END_CONN),
    _f("udf_15", "Pressure Rating",         "Valve Body",      "select", options=_P_RATING),
    _f("udf_16", "Seat Material",           "Trim",            "select",
       options=["SS 316 (metal-to-metal)", "PEEK", "PTFE (soft seat)", "Stellite", "Ceramic"]),
    _f("udf_17", "Leakage Class",           "Trim",            "select", options=_LEAK_CLASS),
    _f("udf_18", "Fire-Safe",               "Trim",            "select", options=_FS_RATE),
    _f("udf_19", "Antistatic Device",       "Trim",            "select", options=["Required", "Not required"]),
    _f("udf_20", "Actuator Type",           "Actuator",        "select", options=_ACT_TYPE),
    _f("udf_21", "Normal Position",         "Actuator",        "select", options=_OPEN_TYPE),
    _f("udf_22", "Fail Position",           "Actuator",        "select", options=_FAIL),
    _f("udf_23", "Closing Time (max s)",    "Actuator",        "number", placeholder="seconds"),
    _f("udf_24", "Opening Time (max s)",    "Actuator",        "number", placeholder="seconds"),
    _f("udf_25", "Air Supply Pressure",     "Actuator",        "number", placeholder="barg"),
    _f("udf_26", "Solenoid Valve",          "Accessories",     "select",
       options=["NAMUR SIL 2", "NAMUR SIL 3", "Dual SOV (1oo2)", "Dual SOV (2oo2)"]),
    _f("udf_27", "Limit Switches",          "Accessories",     "select",
       options=["2 × SPDT (OPEN/CLOSED)", "NAMUR proximity (OPEN)", "NAMUR proximity (CLOSED)",
                "2 × NAMUR proximity (OPEN + CLOSED)", "Not required"]),
    _f("udf_28", "Partial Stroke Testing",  "Accessories",     "select",
       options=["Not required", "By positioner (PST device)", "By SOV cycling"]),
    _f("udf_29", "Power Supply",            "Electrical",      "select", options=_POWER),
    _f("udf_30", "Control Signal",          "Electrical",      "select",
       options=["24 VDC digital (DO)", "110 VAC digital", "4–20 mA (ESD modulated)"]),
    _f("udf_31", "Enclosure IP Rating",     "Electrical",      "select", options=_IP),
    _f("udf_32", "Area Classification",     "Hazardous Area",  "select", options=_HAZOC),
    _f("udf_33", "Gas Group",               "Hazardous Area",  "select", options=_GAS_GRP),
    _f("udf_34", "Temperature Class",       "Hazardous Area",  "select", options=_TEMP_CLS),
    _f("udf_35", "Protection Method",       "Hazardous Area",  "select", options=_EX_METH),
    _f("udf_36", "Certification Body",      "Hazardous Area",  "select", options=_CERT),
    _f("udf_37", "Manufacturer",            "Vendor",          "text"),
    _f("udf_38", "Model / Part Number",     "Vendor",          "text"),
]


# ── PSV — Pressure Safety Valve ───────────────────────────────────────────────
PSV_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "P&ID Number",             "Identification",  "text"),
    _f("udf_03", "Protected Equipment",     "Identification",  "text",   placeholder="e.g. Vessel V-101"),
    _f("udf_04", "Fluid",                   "Process Data",    "text"),
    _f("udf_05", "Fluid State at Inlet",    "Process Data",    "select", options=_PHASE),
    _f("udf_06", "Molecular Weight",        "Process Data",    "number", placeholder="kg/kmol"),
    _f("udf_07", "Compressibility (Z)",     "Process Data",    "number", placeholder="e.g. 0.92"),
    _f("udf_08", "Cp / Cv Ratio (k)",       "Process Data",    "number", placeholder="e.g. 1.28"),
    _f("udf_09", "Density at Inlet",        "Process Data",    "number", placeholder="kg/m³"),
    _f("udf_10", "Temperature at Inlet",    "Process Data",    "number", placeholder="°C"),
    _f("udf_11", "MAWP (barg)",             "Set Conditions",  "number"),
    _f("udf_12", "Set Pressure",            "Set Conditions",  "number", placeholder="barg"),
    _f("udf_13", "Overpressure (%)",        "Set Conditions",  "select",
       options=["10 % (process overpressure)", "16 % (fire case)", "21 % (fire case – dual PRV)"]),
    _f("udf_14", "Superimposed Back Press.","Set Conditions",  "number", placeholder="barg"),
    _f("udf_15", "Built-up Back Pressure",  "Set Conditions",  "number", placeholder="barg"),
    _f("udf_16", "Total Back Pressure",     "Set Conditions",  "number", placeholder="barg (calc'd)"),
    _f("udf_17", "Relieving Rate",          "Sizing",          "number", placeholder="kg/h or Sm³/h"),
    _f("udf_18", "Relieving Rate Unit",     "Sizing",          "select",
       options=["kg/h", "Sm³/h", "MMSCFD", "US gpm", "lb/h"]),
    _f("udf_19", "Required Orifice Area",   "Sizing",          "number", placeholder="cm²"),
    _f("udf_20", "API Orifice Designation", "Sizing",          "select", options=_API_OR),
    _f("udf_21", "Selected Orifice Area",   "Sizing",          "number", placeholder="cm²"),
    _f("udf_22", "Valve Type",              "Valve Body",      "select", options=_PSV_TYPE),
    _f("udf_23", "Manufacturer",            "Valve Body",      "text"),
    _f("udf_24", "Model Number",            "Valve Body",      "text"),
    _f("udf_25", "Inlet Size",              "Valve Body",      "text",   placeholder='e.g. 3" / DN80'),
    _f("udf_26", "Inlet Rating",            "Valve Body",      "select", options=_P_RATING),
    _f("udf_27", "Inlet Connection",        "Valve Body",      "select", options=_END_CONN),
    _f("udf_28", "Outlet Size",             "Valve Body",      "text",   placeholder='e.g. 4" / DN100'),
    _f("udf_29", "Outlet Rating",           "Valve Body",      "select", options=_P_RATING),
    _f("udf_30", "Outlet Connection",       "Valve Body",      "select", options=_END_CONN),
    _f("udf_31", "Body Material",           "Materials",       "select", options=_BODY_MAT),
    _f("udf_32", "Nozzle Material",         "Materials",       "select", options=_BODY_MAT),
    _f("udf_33", "Disc / Piston Material",  "Materials",       "select",
       options=["SS 316L", "Hastelloy C-276", "Monel 400", "Duplex 2205", "PTFE-coated"]),
    _f("udf_34", "Spring Material",         "Materials",       "select",
       options=["Alloy steel (carbon)", "SS 316", "Inconel 718", "Hastelloy C-276"]),
    _f("udf_35", "Bellows Material",        "Materials",       "select",
       options=["N/A (conventional)", "SS 316L", "Hastelloy C-276", "Inconel 625"]),
    _f("udf_36", "Cap Type",                "Accessories",     "select",
       options=["Open (lifting lever)", "Packed (closed)", "Test gag", "Blind flange"]),
    _f("udf_37", "Discharge",               "Accessories",     "select",
       options=["To atmosphere", "Closed relief header", "Flare header", "Knock-out drum"]),
]


# ── AT — Analyzer Transmitter ─────────────────────────────────────────────────
AT_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "P&ID Number",             "Identification",  "text"),
    _f("udf_03", "Measurement Point",       "Identification",  "text"),
    _f("udf_04", "Measured Component(s)",   "Application",     "text",   placeholder="e.g. H₂S, CO₂, O₂"),
    _f("udf_05", "Measurement Principle",   "Application",     "select",
       options=["Electrochemical", "Infrared (NDIR)", "Paramagnetic (O₂)",
                "Photoacoustic IR", "Laser (TDL)", "Gas chromatograph",
                "Flame ionisation (FID)", "Thermal conductivity (TCD)",
                "UV fluorescence", "Chemiluminescence"]),
    _f("udf_06", "Range — Min",             "Application",     "number", placeholder="Lower range value"),
    _f("udf_07", "Range — Max",             "Application",     "number", placeholder="Upper range value"),
    _f("udf_08", "Range Unit",              "Application",     "text",   placeholder="e.g. ppm, %, vol %"),
    _f("udf_09", "Response Time T90 (s)",   "Application",     "number"),
    _f("udf_10", "Sample Conditioning",     "Sample System",   "select",
       options=["Not required (in-situ probe)", "Wet extractive", "Dry extractive (cooled)", "Heated line"]),
    _f("udf_11", "Sample Pressure (barg)",  "Sample System",   "number"),
    _f("udf_12", "Sample Temperature (°C)", "Sample System",   "number"),
    _f("udf_13", "Sample Flow Rate",        "Sample System",   "text",   placeholder="e.g. 1 l/min"),
    _f("udf_14", "Calibration Gas 1",       "Calibration",     "text",   placeholder="e.g. Zero air"),
    _f("udf_15", "Calibration Gas 2",       "Calibration",     "text",   placeholder="e.g. 50 ppm H₂S in N₂"),
    _f("udf_16", "Alarm High (AAH)",        "Calibration",     "number"),
    _f("udf_17", "Alarm Low (AAL)",         "Calibration",     "number"),
    _f("udf_18", "Trip High (AAHH)",        "Calibration",     "number"),
    _f("udf_19", "Manufacturer",            "Analyzer Unit",   "text"),
    _f("udf_20", "Model Number",            "Analyzer Unit",   "text"),
    _f("udf_21", "Enclosure Type",          "Analyzer Unit",   "select",
       options=["Field-mounted (weather-proof)", "Field-mounted (ATEX)", "Shelter-mounted (non-HZ)", "Analyzer house"]),
    _f("udf_22", "Power Supply",            "Electrical",      "select", options=_POWER),
    _f("udf_23", "Output Signal",           "Electrical",      "select", options=_SIGNAL),
    _f("udf_24", "Enclosure IP Rating",     "Electrical",      "select", options=_IP),
    _f("udf_25", "Area Classification",     "Hazardous Area",  "select", options=_HAZOC),
    _f("udf_26", "Gas Group",               "Hazardous Area",  "select", options=_GAS_GRP),
    _f("udf_27", "Temperature Class",       "Hazardous Area",  "select", options=_TEMP_CLS),
    _f("udf_28", "Protection Method",       "Hazardous Area",  "select", options=_EX_METH),
    _f("udf_29", "Certification Body",      "Hazardous Area",  "select", options=_CERT),
]


# ── PSH / PSAH — Pressure Switch ──────────────────────────────────────────────
PSAH_FIELDS = [
    _f("udf_01", "Service Description",     "Identification",  "text"),
    _f("udf_02", "P&ID Number",             "Identification",  "text"),
    _f("udf_03", "Line / Equipment Tag",    "Identification",  "text"),
    _f("udf_04", "Fluid",                   "Process Data",    "text"),
    _f("udf_05", "Operating Pressure",      "Process Data",    "number", placeholder="barg"),
    _f("udf_06", "Design Pressure",         "Process Data",    "number", placeholder="barg"),
    _f("udf_07", "Operating Temperature",   "Process Data",    "number", placeholder="°C"),
    _f("udf_08", "Switch Type",             "Instrument",      "select",
       options=["Bourdon tube", "Piston", "Diaphragm (low pressure)", "Electronic (solid-state)"]),
    _f("udf_09", "Set Point",               "Instrument",      "number", placeholder="barg"),
    _f("udf_10", "Deadband / Reset",        "Instrument",      "number", placeholder="bar"),
    _f("udf_11", "Switch Action",           "Instrument",      "select",
       options=["SPDT (1 × NO + 1 × NC)", "DPDT (2 × NO + 2 × NC)", "SPST (NO)", "SPST (NC)"]),
    _f("udf_12", "Contact Rating",          "Instrument",      "text",   placeholder="e.g. 5A, 250 VAC"),
    _f("udf_13", "Body Material",           "Instrument",      "select", options=_BODY_MAT),
    _f("udf_14", "Process Connection",      "Instrument",      "select", options=_P_CONN),
    _f("udf_15", "Pressure Rating",         "Instrument",      "select", options=_P_RATING),
    _f("udf_16", "Manufacturer",            "Instrument",      "text"),
    _f("udf_17", "Model Number",            "Instrument",      "text"),
    _f("udf_18", "Power Supply",            "Electrical",      "select", options=_POWER),
    _f("udf_19", "Output Signal",           "Electrical",      "select",
       options=["Dry contact (volt-free)", "NAMUR", "4–20 mA (smart switch)"]),
    _f("udf_20", "Enclosure IP Rating",     "Electrical",      "select", options=_IP),
    _f("udf_21", "Area Classification",     "Hazardous Area",  "select", options=_HAZOC),
    _f("udf_22", "Gas Group",               "Hazardous Area",  "select", options=_GAS_GRP),
    _f("udf_23", "Temperature Class",       "Hazardous Area",  "select", options=_TEMP_CLS),
    _f("udf_24", "Protection Method",       "Hazardous Area",  "select", options=_EX_METH),
    _f("udf_25", "Mounting",                "Installation",    "select", options=_MOUNT),
]


# ── Master list ────────────────────────────────────────────────────────────────
SEED_TEMPLATES: list[dict] = [
    # Pressure
    {"template_name": "Pressure Transmitter",              "instrument_type": "PT",   "description": "ISA-aligned PT/PIT spec sheet",           "field_definitions": PT_FIELDS},
    {"template_name": "Pressure Indicating Transmitter",   "instrument_type": "PIT",  "description": "ISA-aligned PIT spec sheet",              "field_definitions": PT_FIELDS},
    {"template_name": "DP Transmitter",                    "instrument_type": "PDT",  "description": "Differential pressure transmitter",       "field_definitions": PDT_FIELDS},
    {"template_name": "Pressure Switch (High/Low)",        "instrument_type": "PSAH", "description": "Pressure switch – alarm and trip",        "field_definitions": PSAH_FIELDS},
    # Flow
    {"template_name": "Flow Transmitter",                  "instrument_type": "FT",   "description": "ISA-aligned FT/FIT spec sheet",           "field_definitions": FT_FIELDS},
    {"template_name": "Flow Indicating Transmitter",       "instrument_type": "FIT",  "description": "ISA-aligned FIT spec sheet",              "field_definitions": FT_FIELDS},
    {"template_name": "Flow Element / Orifice Plate",      "instrument_type": "FE",   "description": "Orifice plate and differential element",   "field_definitions": FE_FIELDS},
    # Level
    {"template_name": "Level Transmitter",                 "instrument_type": "LT",   "description": "ISA-aligned LT/LIT spec sheet",           "field_definitions": LT_FIELDS},
    {"template_name": "Level Indicating Transmitter",      "instrument_type": "LIT",  "description": "ISA-aligned LIT spec sheet",              "field_definitions": LT_FIELDS},
    # Temperature
    {"template_name": "Temperature Transmitter",           "instrument_type": "TT",   "description": "ISA-aligned TT/TIT spec sheet",           "field_definitions": TT_FIELDS},
    {"template_name": "Temperature Indicating Transmitter","instrument_type": "TIT",  "description": "ISA-aligned TIT spec sheet",              "field_definitions": TT_FIELDS},
    {"template_name": "Temperature Element",               "instrument_type": "TE",   "description": "TC/RTD element specification",            "field_definitions": TE_FIELDS},
    {"template_name": "Thermowell",                        "instrument_type": "TW",   "description": "Thermowell — ASME PTC 19.3 aligned",      "field_definitions": TW_FIELDS},
    # Control Valves
    {"template_name": "Control Valve (FCV)",               "instrument_type": "FCV",  "description": "Flow control valve — ISA 75.01 aligned",  "field_definitions": FCV_FIELDS},
    {"template_name": "Control Valve (LCV)",               "instrument_type": "LCV",  "description": "Level control valve",                     "field_definitions": FCV_FIELDS},
    {"template_name": "Control Valve (PCV)",               "instrument_type": "PCV",  "description": "Pressure control valve",                  "field_definitions": FCV_FIELDS},
    # On-Off / Shutdown
    {"template_name": "Shutdown Valve (SDV)",              "instrument_type": "SDV",  "description": "ESD/SDV — IEC 61511 aligned",             "field_definitions": SDV_FIELDS},
    {"template_name": "Blowdown Valve (BDV)",              "instrument_type": "BDV",  "description": "BDV — IEC 61511 aligned",                 "field_definitions": SDV_FIELDS},
    {"template_name": "On-Off Valve (XV)",                 "instrument_type": "XV",   "description": "XV — generic on-off valve",               "field_definitions": SDV_FIELDS},
    # Safety
    {"template_name": "Pressure Safety Valve (PSV)",       "instrument_type": "PSV",  "description": "PSV — API 520/521/526 aligned",           "field_definitions": PSV_FIELDS},
    # Analyzer
    {"template_name": "Analyzer Transmitter",              "instrument_type": "AT",   "description": "Generic analyzer transmitter",            "field_definitions": AT_FIELDS},
]
